Repository JoaoDanielRufino/gcloc, pull requests merged in 2022-10, with the labels that each got.

#30 Add C language code sample for tests
  pkg/analyzer/analyzer_test.go
  pkg/scanner/scanner_test.go
  test/fixtures/code_samples/_main.c
Labels: hacktoberfest

#36 Fix analyzer and scanner tests
  pkg/analyzer/analyzer_test.go
  pkg/scanner/scanner_test.go
Labels: bug

#43 add python
  pkg/analyzer/analyzer_test.go
  pkg/scanner/scanner_test.go
  test/fixtures/code_samples/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#45 Add ruby code sample for test (#40)
  pkg/analyzer/analyzer_test.go
  pkg/scanner/scanner_test.go
  test/fixtures/code_samples/main.rb
Labels: hacktoberfest, hacktoberfest-accepted

#46 Add Kotlin code sample for tests.
  pkg/analyzer/analyzer_test.go
  pkg/scanner/scanner_test.go
  test/fixtures/code_samples/Main.kt
Labels: hacktoberfest, hacktoberfest-accepted

#52 feat(json): add tests
  pkg/analyzer/analyzer_test.go
  pkg/scanner/scanner_test.go
  test/fixtures/code_samples/hello.json
Labels: hacktoberfest, hacktoberfest-accepted

#53 feat(php): add test
  pkg/analyzer/analyzer_test.go
  pkg/scanner/scanner_test.go
  test/fixtures/code_samples/main.php
Labels: hacktoberfest, hacktoberfest-accepted

#54 Add Vue fixture.
  pkg/analyzer/analyzer_test.go
  pkg/scanner/scanner_test.go
  test/fixtures/code_samples/App.vue
Labels: hacktoberfest, hacktoberfest-accepted

#56 Add makefile code sample for tests
  pkg/analyzer/analyzer_test.go
  pkg/scanner/scanner_test.go
  test/fixtures/code_samples/Makefile
Labels: hacktoberfest, hacktoberfest-accepted

#64 Create yaml test file
  pkg/analyzer/analyzer_test.go
  pkg/scanner/scanner_test.go
  test/fixtures/code_samples/example.yml
Labels: hacktoberfest, hacktoberfest-accepted

#66 add plaintext sample
  pkg/analyzer/analyzer_test.go
  pkg/scanner/scanner_test.go
  test/fixtures/code_samples/fernando-pessoa.txt
Labels: hacktoberfest, hacktoberfest-accepted
